apiVersion: v1
kind: Service
metadata: 
    name: expressservice
spec: 
  type: NodePort
  selector: 
      app: expressapp
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30018 
